# Generated by Django 3.2.4 on 2021-06-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='mome',
            new_name='nome',
        ),
    ]
