# Generated by Django 3.2.4 on 2021-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_mome_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostar',
            field=models.BooleanField(default=True),
        ),
    ]
